### ISSUE TITLE
Add preferred citation

### ISSUE THREAD

**Issue by bsipocz** [hipspy/hips#118]
Please add the preferred citation somewhere to the documentation (and preferable also to a CITATION file)

**Comment by adl1995** [comment]
@bsipocz Do you mean to cite the HiPS paper? Something similar to what Astropy does (https://github.com/astropy/astropy/blob/master/CITATION)?

A mention to the HiPS paper (with the link) is currently provided in the About section (https://hips.readthedocs.io/en/latest/about.html).

**Comment by bsipocz** [comment]
I'm not sure what the most appropriate thing to cite here, with other packages we usually do a zenodo entry for a release and cite that when there is no paper about the package. 

@cdeil - what do you  think, should I cite the hips paper or wait for a zenodo in the astropy paper?

**Comment by cdeil** [comment]
Citing the HIPS paper is not appropriate, it is different from this package. If a citation is given it should be to the https://github.com/hipspy/hips URL for now. If that is not possible in your table, then no citation should be given for now.

I'm not a fan of just throwing releases on Zenodo and generating DOIs. I fail to see how that is useful. Instead, a real writeup of what a project is and submitting to https://joss.theoj.org/ is useful IMO. But that's a bit of work and for the future. For now, we don't have a paper about the hips package.

**Comment by cdeil** [comment]
@bsipocz - If you need a bibtex entry to cite something about this package from the AStropy paper, and just putting a URL there doesn't work, then I'd suggest you put this:
```
@MISC{hips,
  author = {hips developers},
  title = {hips -- Python library to handle HiPS data},
  howpublished = {\url{https://github.com/hipspy/hips}},
}
```

**Comment by bsipocz** [comment]
@cdeil - I'll try to go with the URL, will see whether the editors like it.

**Comment by bsipocz** [comment]
@cdeil - Just a follow-up on this:

> I'm not a fan of just throwing releases on Zenodo and generating DOIs. I fail to see how that is useful. Instead, a real writeup of what a project is and submitting to https://joss.theoj.org/ is useful IMO. But that's a bit of work and for the future. For now, we don't have a paper about the hips package.

I just heard that indexing zenodo for these references is in the work at ADS, so sometimes pretty soon these citations will be picked up. 🎉

**Comment by cdeil** [comment]
I think we should publish in https://joss.theoj.org/ . I've never done it, but my understanding is that one simply writes a `paper/paper.md` file in this repo, plus another file with bibtex references, and that it can be just 1 page.

@adl1995 - Do you still have time for hipspy and might be interested to write and submit a JOSS 1-page article?

@tboch and I will work a bit on `hipspy` next week, and we could cut a v0.3 release at the end of next week and write this 1 page.

**Comment by adl1995** [comment]
@cdeil Yes, I have some free time during this week. I'd be happy to submit a JOSS article.

I will create a draft and share it here. I think the article can include the following headings:

- Summary
  - Design rationale
  - Algorithms / techniques used
- Examples (can also provide results)
- Acknowledgments
- References

Please let me know if it should contain any other details.

**Comment by cdeil** [comment]
@adl1995 - Great! Please go ahead. I'd suggest to really start with a minimal 1-page draft, and then only expand a bit maybe, after discussion. I would suggest to add a mention of other HiPS tools, like Aladin Lite and ipyaladin and hipsgen, and briefly describe the scope and use case for this Python package and where one might want to use it. (Basically: where one wants a lot of flexibility and scriptability to do HiPS -> WCS image or soon also HiPS <-> WCS or HEALPix image. Maybe be very brief on the algorithms used here and an example, because the algorithm and API are still in development.

I'm not sure yet what would be the best time to publish. Of course we could do it now and describe v0.2. Or we could wait a bit and describe v0.3. Given that this isn't a very large and active project, I don't think we will ever publish another paper, so we shouldn't do it too early (but also not too late).

**Comment by adl1995** [comment]
I have opened a pull request ([#125](https://github.com/hipspy/hips/pull/125)) which adds the JOSS article.

Regarding v0.3 release, do all the milestones listed [here](https://github.com/hipspy/hips/milestone/5) need to be addressed? Or, is there any additional functionality that should be added as well?

I think most of the currently opened issues are already addressed, but some need further improvements. I can continue with the code I was previously working on during GSoC (cf. [#79](https://github.com/hipspy/hips/issues/79), [#103](https://github.com/hipspy/hips/issues/103), [#108](https://github.com/hipspy/hips/pull/108)). It would be nice to address the bright tile edges issue before the paper is published, as it will make the output more 'clean'.

**Comment by cdeil** [comment]
I'm closing this issue, let's discuss in #125 .

Concerning v0.3 and open issues / tasks: I don't know.
@adl1995 - If you have a bit of time for coding also, I think the most efficient would be if we have a short Skype call and look over the old open PRs / issues.

Yes, the draw needs to be fixed for sure, it's really not nice output and terribly slow.
