### ISSUE TITLE
ImportError: cannot import name 'WCSGeometry'

### ISSUE THREAD

**Issue by ggreco77** [hipspy/hips#121]
Hi,
after installing hips (python3.6.3 in centos7) I get the following error during the check installation

_File "/users/greco/hips.py", line 2, in <module>
from hips import WCSGeometry
ImportError: cannot import name 'WCSGeometry'_

thanks for such effort.

**Comment by cdeil** [comment]
I think the issue might be that you have named your script `/users/greco/hips.py`, i.e. the same name as the `hips` package. 

Try renaming to e.g. `/users/greco/hips_example.py`.

If this doesn't help, what is your version?
```
python -c 'import hips; print(hips.__version__)'
```

**Comment by ggreco77** [comment]
I did not rename the script; however also using the statement above I get the same issue ->
  File "<string>", line 1, in <module>
  File "/users/greco/hips.py", line 2, in <module>
    from hips import WCSGeometry
ImportError: cannot import name 'WCSGeometry'

thanks,
giuseppe

**Comment by cdeil** [comment]
> I did not rename the script

Why not? Please try it.

Also, please paste not just part of the traceback, but show everything: the command you ran (probably `python hips.py`?) and the complete traceback.

**Comment by ggreco77** [comment]
ah, ok sorry for misanderstaiding -> I rename the script *hips.py* in *hips_example.py* in my home dir and I type
 ` python3 hips_example.py`
now the error is different;
_Traceback (most recent call last):
  File "hips_example.py", line 2, in <module>
    from hips import WCSGeometry
ImportError: bad magic number in 'hips': b'\x03\xf3\r\n'_

**Comment by adl1995** [comment]
@ggreco77 This is probably because the `.pyc` files present in the hips repository are damaged. Please try re-installing the package:
```
$ pip uninstall hips
```
And then install again:
```
$ pip install hips --no-deps
```
Another solution is to manually remove the `.pyc` files (so Python can generate them again). First `cd` into the directory where hips is installed. For me, it is:
```
$ cd /home/adeel/anaconda3/lib/python3.6/site-packages/hips
```
You can also locate the directory by typing:
```
$ locate python3.6/site-packages/hips
```
Finally, delete the `.pyc` files:
```
$ find . -name \*.pyc -delete
```

**Comment by ggreco77** [comment]
Many thanks. Now it works fine by removing .pyc files.
