### ISSUE TITLE
how to make a hips plot without the tile boundaries plotted 

### ISSUE THREAD

**Issue by richardgmcmahon** [hipspy/hips#130]
I am using the example plot_fits.py with a smaller fov:

https://github.com/hipspy/hips/blob/master/docs/getting_started.rst

width=360, height=360, fov="0.1 deg"

See attached png; How do I NOT get the tile boundaries plotted?

help(make_sky_image) does not tell me:

help(plot) tells me that the tiles arre are plotted but not how to NOT plot them
plot(self) -> None
 |      Plot the all sky image and overlay HiPS tile outlines.
```
result.plot()
# Draw the sky image
import matplotlib.pyplot as plt
from astropy.visualization.mpl_normalize import simple_norm
ax = plt.subplot(projection=geometry.wcs)
norm = simple_norm(result.image, 'sqrt', min_percent=1, max_percent=99)
ax.imshow(result.image, origin='lower', norm=norm, cmap='gray')

import matplotlib.pyplot as plt
plt.savefig('hips.png')
plt.show()
```
![hips](https://user-images.githubusercontent.com/2388403/43040905-0c22960c-8d49-11e8-9629-7199e6e305b9.png)

If I do not call result.plot() before the plt sequence I get:

![hips](https://user-images.githubusercontent.com/2388403/43040945-561ae2b8-8d4a-11e8-9af1-13aace57e89e.png)

So somewhere behind the scenes some matplotlib hidden magic is taking place. e.g. is make_sky_image doing some matplotlib work

As well as turning of the tile boundaries, it could be useful to know how to specify line color and line style for the tile boundaries too.

**Comment by adl1995** [comment]
@cdeil - Would adding a section on "Plot using Astropy visualization toolkit" in the "Getting started" page be enough? We could redirect users to Astropy docs for further reading.

What sort of example should we provide using the `astropy.visualization` package? Currently, the example in the docs has this snippet:
```python
from astropy.visualization.mpl_normalize import simple_norm
ax = plt.subplot(projection=geometry.wcs)
norm = simple_norm(result.image, 'sqrt', min_percent=1, max_percent=99)
ax.imshow(result.image, origin='lower', norm=norm, cmap='gray')
```

Which produces this plot:
![astropy_plot](https://user-images.githubusercontent.com/13198325/43075478-713651bc-8e9a-11e8-8a94-3b7066eca2c3.png)

**Comment by cdeil** [comment]
OK, if you want to keep the current single high-level docs page approach for now.

A key point to make is that usually grayscale / FITS images are plotted differently than RGB images.

For grayscale / FITS usually one will want to control the stretch, as you show in the example already.

For RGB, usually one will want to plot the pixels "as-is", without applying an extra stretch.
(although one could if desired)

In both cases, one can just save images / pixels as-is (mpl imsave), or plot using axes (mpl imshow / wcsaxes).

So really there's four cases / examples how to plot (float greyscale vs RGB input; and imsave vs imshow with MPL plotting).

Improving the docs on this plotting could go hand in hand with addressing https://github.com/hipspy/hips/issues/40, i.e. explaining what the output images contain.

(for RGB it's uint8 values in the range 0 to 255, plus in the case of PNG a transparency channel)

The documentation on this in this hips package can be short, linking to the astropy.visualisaiton or scikit-iamge docs where useful; but it really should be improved to make it clearer to users what they get out and how to work with it.

**Comment by cdeil** [comment]
Done by @adl1995 in  #131 .
