### ISSUE TITLE
UTF-8 decode invalid start byte error

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips#29]
This issue concerns [#27](https://github.com/hipspy/hips/pull/27). When a byte is decoded using: `text = response.decode('utf-8')`, this error comes up:

` UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 83958: invalid start byte `

For now the workaround is to simply use `str(response)`.

**Comment by cdeil** [comment]
I fixed this here: https://github.com/hipspy/hips/pull/27/files#diff-0fe71e698f361724cee17a858a30ebc0R71

Simply calling `str(response)` doesn't work properly, it inserts this repr for the bytes string that starts with "b" into the string. Example:
```python
>>> str(b'spam')
"b'spam'"
```
