### ISSUE TITLE
Set up Windows testing on Appveyor

### ISSUE THREAD

**Issue by cdeil** [hipspy/hips#3]
Reminder issue for myself to set up windows testing on Appveyor.

**Comment by cdeil** [comment]
A windows build on Appveyor is now running for this project.

It starts failing here:
https://ci.appveyor.com/project/cdeil/hips/build/1.0.4#L86
and then healpy isn't installed by conda and pip install healpy fails.

@bsipocz -- Again the question - is this an issue I introduced in `appveyor.yml` or an issue with the `package-template`? Can you help and make it better?

**Comment by bsipocz** [comment]
There is no conda build for healpy and numpy 1.13. This case ci-helpers tries to install the packages with pip, but I simply guess that is not possible for healpy on windows? I'll change the numpy version in a joint PR with #6.

**Comment by cdeil** [comment]
This is done. Windows build on Appveyor is working since / thanks to the switch to astropy-healpix: #109 . I'll make a v0.2 release now to get this change / added platform support available for users.
