### ISSUE TITLE
Reformating SimpleTilePainter class

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips#57]
As discussed during our telecon on July 5th, the `SimpleTilePainter` class needs to be reformated to exactly outline the steps mentioned in the [drawing algorithm](http://hips.readthedocs.io/en/latest/drawing_algo.html). The current suggestions are outlined below:

- Move tile list computation part within `SimpleTilePainter`
- `SimpleTilePainter` should be passed in a list of tiles instead of a single tile
- Methods should be converted into properties and there should be a method named `run` which executes all steps in order
- Add unit tests for all the intermediate values computed in `SimpleTilePainter` class

@tboch @cdeil - If you have any other suggestions, please share.

**Comment by cdeil** [comment]
> SimpleTilePainter should be passed in a list of tiles instead of a single tile

I would suggest that the painter is responsible for all steps, even tile list computation and fetching.
Internally it would eventually create a `HipsTileCache` and call it to fetch and store the tiles, for now it calls out to the compute tiles needed and fetch tiles needed functions.

I.e. it gets initialised just with the user spec of geometry and which HiPS to use (at the moment represented by a `HipsSurveyProperties` object, and then runs all the steps from the drawing algorithm description.

**Comment by cdeil** [comment]
Done by @adl1995 in #66 .
