### ISSUE TITLE
Drawing JPG, PNG tiles

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips#62]
For drawing the higher dimensional tiles such as JPG and PNG, the empty image's shape in `draw_sky_image` would have to be altered. This `shape` currently comes from `WCSGeometry` class. However, this is always 2 dimensional. To handle multi-dimentional tiles, I'm thinking of adding them manually, i.e. 3 extra dimensions in case of JPG tiles and 4 extra dimensions in case of PNG tiles.

@cdeil @tboch If you have an alternative / better suggestion, please share.

**Comment by cdeil** [comment]
> For drawing the higher dimensional tiles such as JPG and PNG, the empty image's shape in draw_sky_image would have to be altered. This shape currently comes from WCSGeometry class. However, this is always 2 dimensional.

For drawing RGB images, two different shapes are needed in different places of the code:
* The 3-dim shape of the ``data`` -- used e.g. when creating the empty sky image array at the start of the drawing.
* The 2-dim shape, with the third dimension dropped -- used e.g. to compute the transform (I assume scikit-image wants 2D here and can't handle 3D directly, but I'm not sure, you should try).

> To handle multi-dimentional tiles, I'm thinking of adding them manually, i.e. 3 extra dimensions in case of JPG tiles and 4 extra dimensions in case of PNG tiles.

I don't know how to handle this best yet, and I have no idea what you mean by "adding them manually".
My suggestion is that you start a PR, start by adding a (failing) test case  and then try to do minimal changes to the existing code to make it work for RGB images, asking for help on the PR as you go.

The core question is if the scikit-image warp function can process 3-dim or not.
* If yes, then maybe you just need to make the 2-dim shape when computing the transform (dropping the RGB dimension)?
* If no, then probably you need to do a Python loop over the RGB channels, and draw one after the other.

@adl1995 - Does this help you get started?

**Comment by cdeil** [comment]
Implemented by @adl1995  in #63
