### ISSUE TITLE
Incorrect corner order of HiPS during stitching

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips#74]
This issue relates with incorrect order for HiPS tiles, this leads to incorrect stitching of tiles. The notebook related with this can be found here (https://github.com/adl1995/HIPS-to-Py/blob/master/examples/JPG_tile_draw_issue.ipynb).

**Comment by cdeil** [comment]
Related issue with infos from Thomas: #18

**Comment by cdeil** [comment]
I think I found the origin of the tile corner order issue. with JPG and PNG, the tile images are flipped in the y direction. See Figure 6 in http://www.ivoa.net/documents/HiPS/20160623/WD-HiPS-1.0-20160623.pdf

I'll make a PR today.

**Comment by cdeil** [comment]
Fixed in #78
